### ISSUE TITLE
Integration Test Failing: ContainerExecuteCommand_WhenCalled_ExpectResultsToBeReturned

### ISSUE THREAD

**Issue by Frueber** [ktmitton/Mittons.Fixtures#26]
**Issue**: When running the project locally I'm seeing all tests pass (green) except for `ContainerExecuteCommand_WhenCalled_ExpectResultsToBeReturned`.
It looks like this test was added, and started off in a failing state, in commit `84dfc53cebd6e8d21676dca35f9ad55ec5bc20da`.

**Test Result**: "The collection was expected to contain a single element, but it was empty."

**Comment by ktmitton** [comment]
I think I figured out the issue, it's a timing issue, the container is not finished spinning up so commands are failing.

I'm going to create a test case that shows this, the fix is then to implement a health check. I think we're also getting close to needing to move some of the work out of the constructor and create something like IApplicationLifetime.

**Comment by ktmitton** [comment]
Dropping this here so I don't forget, ssh will need something like this for the healthcheck:
ps aux | grep -v grep | grep sshd || exit 1

**Comment by ktmitton** [comment]
@Frueber I think it closed automatically since I marked it "Fixes #27" in the PR, didn't expect that. Reopening until you can confirm, do all the tests run now?

**Comment by Frueber** [comment]
> @Frueber I think it closed automatically since I marked it "Fixes #27" in the PR, didn't expect that. Reopening until you can confirm, do all the tests run now?

Everything is passing for me now as well :). I see the fix was a delay, yeah? It sounds like you might have been talking about a different approach long-term?

**Comment by ktmitton** [comment]
yeah, the problem is we're doing container actions before the container is done spinning up, so we need to start implementing a health check. #28 is meant to address this, so we'd be able to get rid of the "good enough delay".

**Comment by ktmitton** [comment]
@Frueber I can't seem to tag you in the PR, can you take a look at PR #30 , that's my initial approach for StartAsync on containers. In particular, I'm not quite happy with where I put IServiceLifetime, so any suggestions on namespace/folder structure is appreciated!

**Comment by ktmitton** [comment]
@Frueber I'm going to commit that PR so I can keep moving, if there are changes you think could be made, let me know and we can open another PR!
