### ISSUE TITLE
Replace KeyValuePair with tuple

### ISSUE THREAD

**Issue by ktmitton** [ktmitton/Mittons.Fixtures#74]
Look into uses of KeyValuePair and replace them with tuples where it makes sense.

**Comment by ktmitton** [comment]
If it makes sense, models are also an option

**Comment by Frueber** [comment]
Here's something I was going to take a look at with regards to KeyValuePair vs Tuple (and ValueTuple).
https://gist.github.com/ljw1004/61bc96700d0b03c17cf83dbb51437a69

**Comment by ktmitton** [comment]
> Here's something I was going to take a look at with regards to KeyValuePair vs Tuple (and ValueTuple). https://gist.github.com/ljw1004/61bc96700d0b03c17cf83dbb51437a69

Not a bad idea, curios what you find!
